# Stage 1: Build frontend (uses `admin-dashboard` folder)
FROM node:20-alpine AS frontend-builder
WORKDIR /admin-dashboard
COPY admin-dashboard/package*.json ./
RUN npm install
COPY admin-dashboard/ .
RUN npm run build

# Stage 2: Nginx sirve el frontend + gateway a los microservicios
FROM nginx:alpine
COPY --from=frontend-builder /admin-dashboard/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
