[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=info
user=root

[program:rabbitmq]
command=/usr/sbin/rabbitmq-server
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:auth-service]
command=node dist/app.js
directory=/app/services/auth-service
autostart=true
autorestart=true
priority=30
environment=PORT="3001",GRPC_PORT="4001"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:inventario-service]
command=node dist/app.js
directory=/app/services/inventario-service
autostart=true
autorestart=true
priority=30
environment=PORT="3002",GRPC_PORT="4004"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:org-service]
command=node dist/app.js
directory=/app/services/org-service
autostart=true
autorestart=true
priority=30
environment=PORT="3003",GRPC_PORT="4007"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:operaciones-service]
command=node dist/app.js
directory=/app/services/operaciones-service
autostart=true
autorestart=true
priority=30
environment=PORT="3004",INVENTARIO_SERVICE_URL="http://127.0.0.1:3002",INVENTARIO_GRPC_HOST="127.0.0.1",INVENTARIO_GRPC_PORT="4004"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:financiero-service]
command=node dist/app.js
directory=/app/services/financiero-service
autostart=true
autorestart=true
priority=40
environment=PORT="3005",GRPC_PORT="4003",RABBITMQ_URL="amqp://guest:guest@127.0.0.1:5672"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:mantenimiento-service]
command=node dist/app.js
directory=/app/services/mantenimiento-service
autostart=true
autorestart=true
priority=40
environment=PORT="3006",RABBITMQ_URL="amqp://guest:guest@127.0.0.1:5672"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:bus-service]
command=node dist/app.js
directory=/app/services/bus-service
autostart=true
autorestart=true
priority=50
environment=PORT="3007",RABBITMQ_URL="amqp://guest:guest@127.0.0.1:5672",OPERACIONES_SERVICE_URL="http://127.0.0.1:3004",INVENTARIO_SERVICE_URL="http://127.0.0.1:3002",FINANCIERO_SERVICE_URL="http://127.0.0.1:3005"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
